-- =====================================================================
-- health schema — vitamin / medication / supplement tracking
-- =====================================================================
-- Run once against garmin_sync:
--   psql "postgresql://garmin_user:...@localhost:5432/garmin_sync" -f health_schema.sql
--
-- Everything is owned by garmin_user → full write access for both the
-- addon process and the client (same role).  All objects use IF NOT
-- EXISTS / CREATE OR REPLACE so the file is safe to re-run.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS health AUTHORIZATION garmin_user;

-- ---------------------------------------------------------------------
-- 1.  manufacturer  — supplement / medication producers
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.manufacturer (
    manufacturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    website         TEXT,
    country         TEXT,
    notes           TEXT,
    create_ts       TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_ts       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 2.  supplement  — master catalogue of every vitamin, mineral,
--     medication and other product you own
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.supplement (
    supplement_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT NOT NULL,
    brand_name          TEXT,
    manufacturer_id     BIGINT REFERENCES health.manufacturer(manufacturer_id)
                            ON DELETE SET NULL,
    category            TEXT NOT NULL DEFAULT 'supplement',
                        -- vitamin | mineral | supplement | medication | herb | other
    form                TEXT,
                        -- tablet | capsule | softgel | liquid | powder | gummy |
                        -- spray | drop | chew | bar | shot
    strength_amount     NUMERIC,
    strength_unit       TEXT,
                        -- mg | mcg | IU | g | ml | % | CFU
    servings_per_container INTEGER,
    barcode             TEXT,
    external_ref        TEXT,
    notes               TEXT,
    active              BOOLEAN NOT NULL DEFAULT true,
    create_ts           TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_ts           TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN health.supplement.external_ref IS
    'Free-form external ID, e.g. a URL slug, Garmin activity-type key, or barcode-system code';

-- ---------------------------------------------------------------------
-- 3.  supplement_ingredient  — nutrient breakdown per product
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.supplement_ingredient (
    ingredient_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id       BIGINT NOT NULL REFERENCES health.supplement(supplement_id)
                            ON DELETE CASCADE,
    nutrient            TEXT NOT NULL,
    amount              NUMERIC,
    unit                TEXT,
    percent_daily_value NUMERIC,
    create_ts           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 4.  inventory  — stock levels, expiry, low-stock thresholds
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.inventory (
    inventory_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id        BIGINT NOT NULL REFERENCES health.supplement(supplement_id)
                             ON DELETE CASCADE,
    quantity_remaining   NUMERIC,
    unit                 TEXT,       -- tablet | capsule | ml | dose | scoop
    expiry_date          DATE,
    purchase_date        DATE,
    lot_number           TEXT,
    low_stock_threshold  NUMERIC,
    notes                TEXT,
    update_ts            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 5.  schedule  — daily / recurring supplement plan
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.schedule (
    schedule_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id   BIGINT NOT NULL REFERENCES health.supplement(supplement_id)
                        ON DELETE CASCADE,
    dose_amount     NUMERIC NOT NULL DEFAULT 1,
    dose_unit       TEXT NOT NULL DEFAULT 'tablet',
    frequency_type  TEXT NOT NULL DEFAULT 'daily',
                    -- daily | specific_days | interval_days | times_per_day | as_needed
    days_of_week    SMALLINT[],
                    -- 0 = Monday … 6 = Sunday
    interval_days   INTEGER,
    start_date      DATE NOT NULL DEFAULT current_date,
    end_date        DATE,
    with_food       BOOLEAN,
    instructions    TEXT,
    active          BOOLEAN NOT NULL DEFAULT true,
    create_ts       TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_ts       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 6.  schedule_time  — time slots within a schedule (multiple per day)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.schedule_time (
    schedule_time_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id      BIGINT NOT NULL REFERENCES health.schedule(schedule_id)
                         ON DELETE CASCADE,
    time_of_day      TIME NOT NULL,
    dose_amount      NUMERIC,
    label            TEXT,
    UNIQUE (schedule_id, time_of_day)
);

-- ---------------------------------------------------------------------
-- 7.  intake_log  — whether a scheduled dose was taken (or skipped)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS health.intake_log (
    intake_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id       BIGINT NOT NULL REFERENCES health.supplement(supplement_id)
                            ON DELETE CASCADE,
    schedule_id         BIGINT REFERENCES health.schedule(schedule_id)
                            ON DELETE SET NULL,
    scheduled_date      DATE NOT NULL DEFAULT current_date,
    scheduled_ts        TIMESTAMPTZ,
    status              TEXT NOT NULL DEFAULT 'pending',
                        -- taken | skipped | missed | pending
    taken_ts            TIMESTAMPTZ,
    dose_amount_taken   NUMERIC,
    notes               TEXT,
    source              TEXT NOT NULL DEFAULT 'client',
                        -- client | garmin | manual
    create_ts           TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_ts           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_supp_ingredient_supp
    ON health.supplement_ingredient (supplement_id);
CREATE INDEX IF NOT EXISTS ix_inventory_supp
    ON health.inventory (supplement_id);
CREATE INDEX IF NOT EXISTS ix_schedule_supp
    ON health.schedule (supplement_id);
CREATE INDEX IF NOT EXISTS ix_intake_supp_date
    ON health.intake_log (supplement_id, scheduled_date);
CREATE UNIQUE INDEX IF NOT EXISTS ux_intake_sched_ts
    ON health.intake_log (schedule_id, scheduled_ts)
    WHERE schedule_id IS NOT NULL AND scheduled_ts IS NOT NULL;

-- ---------------------------------------------------------------------
-- View  health.daily_vitamins  — today's plan with intake status
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW health.daily_vitamins AS
SELECT
    s.schedule_id,
    sup.supplement_id,
    sup.name,
    sup.brand_name,
    st.time_of_day,
    st.label   AS time_label,
    COALESCE(st.dose_amount, s.dose_amount) AS dose_amount,
    s.dose_unit,
    s.with_food,
    s.instructions,
    current_date AS day,
    il.intake_id,
    COALESCE(il.status, 'pending') AS status,
    il.taken_ts
FROM health.schedule s
JOIN health.supplement sup
    ON sup.supplement_id = s.supplement_id
LEFT JOIN health.schedule_time st
    ON st.schedule_id = s.schedule_id
LEFT JOIN health.intake_log il
    ON il.schedule_id  = s.schedule_id
   AND il.scheduled_date = current_date
WHERE s.active
  AND s.start_date <= current_date
  AND (s.end_date IS NULL OR s.end_date >= current_date)
  AND (
       s.frequency_type IN ('daily', 'times_per_day', 'as_needed')
    OR (s.frequency_type = 'specific_days'
        AND (EXTRACT(ISODOW FROM current_date)::INT - 1) = ANY(s.days_of_week))
    OR (s.frequency_type  = 'interval_days'
        AND s.interval_days IS NOT NULL
        AND s.interval_days > 0
        AND ((current_date - s.start_date) % s.interval_days) = 0)
  );

COMMIT;
